# Generated by Django 4.2.6 on 2023-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0003_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quentity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
